### ISSUE TITLE
Calendars selection not saved

### ISSUE THREAD

**Issue by ismslv** [pakerwreah/Calendr#100]
I use multiple calendars from iCloud, Google and some custom domains. Some of them I do not need, some of them double the others. The selection is not saved in the following cases:

- if I deselect some calendars from the popover menu and then open app settings, all the calendars are selected
- If I make a selection in settings, popover menu reflect these changes
- But when I reload the app, all calendars are selected again, this nothing was saved (or was not loaded)

I made multiple tests and this happens from time to time.

**Comment by pakerwreah** [comment]
If you unselect every calendar, the app shows everything. That's sort of an intended behavior, because the first time you open the app you have no selection. But I will do something about it, as it can be a little confusing.

I'm not sure if that's what you are experiencing though.

**Comment by ismslv** [comment]
> If you unselect every calendar, the app shows everything.
> I'm not sure if that's what you are experiencing though.

I unselected only half of the calendars.

**Comment by pakerwreah** [comment]
Damn! This is a bug introduced in v1.7.0 when I removed the RxRelay dependency.
After any event/reminder change, the calendar picker would completely stop working. 🤦🏻‍♂️ 
Very very nasty bug. Thanks for reporting 🙏🏻
