### ISSUE TITLE
Click to create

### ISSUE THREAD

**Issue by ismslv** [pakerwreah/Calendr#101]
I understand that task/reminder creation dialog would be too complex and too non-minimalist, but is it possible to add some url-schema or apple script to launch new task/reminder creation in the corresponding app? For example, Opt+Click on Calendar or Reminders icon could do that.

**Comment by pakerwreah** [comment]
I've searched all over the internet (a while ago) for "how to open an event in the Calendar app", but I didn't find it.
But I think creating a new event is pretty common 🤔 (not sure about reminders though)
I will see if I can figure this out. 💡

**Comment by pakerwreah** [comment]
What makes me very disappointed is that there's a native ViewController for iOS to do that, but not for macOS 😒

**Comment by ismslv** [comment]
The first idea is to use applescript.
AppleScript editor > File > Open Dictionary... > Select Calendar or Reminders app.

This is what I've found for example. There are commands to open, show, make etc.

<img src="https://i.ibb.co/wKXgfn8/Screenshot-2022-12-15-at-17-47-10.png" />

<img src="https://i.ibb.co/PF1HHwf/Screenshot-2022-12-15-at-17-48-24.png" />

**Comment by pakerwreah** [comment]
I managed to do it, but that very quickly became a permission dialog hell. (a total of 5)
That brings little benefit and it's really not the point of the app.
On top of that, macOS caches those permissions in a weird way, making it a nightmare for testing.
