### ISSUE TITLE
App does not auto start on login

### ISSUE THREAD

**Issue by Dev-ManishTomar** [pakerwreah/Calendr#105]

**Comment by pakerwreah** [comment]
I will see if I can add this feature, but I'm not sure if it will work for non-signed apps.
In the meanwhile you can just go to `System Settings -> General -> Login Items` and add the app there.

**Comment by pakerwreah** [comment]
Could you please check if this works for you?
[Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/10321912/Calendr.app.zip)

**Comment by pakerwreah** [comment]
Please help me test this @gferreroferri @ismslv 🙏🏻 
This was terrible to implement before macOS Ventura, now it's quite easy, but I'm second guessing how easy it was.

**Comment by Dev-ManishTomar** [comment]
Yes, it works, I just installed it but have not tested the 'Start at login' Functionality.
________________________________
