### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by Albiji** [pakerwreah/Calendr#107]
How can I help to translate in Italian?

**Comment by pakerwreah** [comment]
Hello! 👋🏻 

If you want to open a PR, you can see all the translations here:
https://github.com/pakerwreah/Calendr/tree/master/Calendr/Assets
Just create a new folder named `it.lproj` and put your `Localizable.strings` inside.

If not, you can just copy this file:
https://github.com/pakerwreah/Calendr/blob/master/Calendr/Assets/en.lproj/Localizable.strings
...edit it and attach the result here.

**Comment by Albiji** [comment]
[it.lproj.zip](https://github.com/pakerwreah/Calendr/files/10450006/it.lproj.zip)

**Comment by pakerwreah** [comment]
Thanks! It will be included in the next release.

**Comment by Albiji** [comment]
there was an error.. this file is better...
I can't understand why ( in your beautiful app) my reminder not completed with a date of past, appear twice in today list and in the past date of the reminder.  

Anyway, here you are... if I find other mistake or adjustments I upload again...

[it.lproj.zip](https://github.com/pakerwreah/Calendr/files/10463718/it.lproj.zip)

**Comment by pakerwreah** [comment]
Could you open a new issue with more information and some screenshots?

**Comment by pakerwreah** [comment]
Oh, I think I know what you mean. This is actually a feature. Overdue reminders always appear in today's view.
I guess if you're not planning to complete it, maybe it makes more sense to delete it, right?

**Comment by pakerwreah** [comment]
But I actually found an issue where the overdue reminder would show twice in Today's view if it was a full day reminder ☝🏻
