### ISSUE TITLE
Be able to configure date string on menu bar

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#11]
Be able to configure the date string on the menu bar using format such EE dd mm etc.

**Comment by pakerwreah** [comment]
Most of the users won't know how to configure those formats.

You can change the formats in System Preferences > Language & Region > Advanced:

<img width="668" alt="Screenshot 2021-02-19 at 10 27 07" src="https://user-images.githubusercontent.com/803954/108510254-0a1c7080-729d-11eb-8417-b7b10b1e6df6.png">

**Comment by gferreroferri** [comment]
OK. Clear

**Comment by pakerwreah** [comment]
This panel does not exist in macOS Ventura.
If it ever comes back, we can still use it.
I've added a new option in v1.6.7 that allows us to specify a custom date format as originally requested.

<img width="276" alt="Screenshot 2022-11-04 at 21 00 56" src="https://user-images.githubusercontent.com/803954/200074128-2c248626-1018-48dc-9687-24001a8e046b.png">

**Comment by gferreroferri** [comment]
Thanks!
