### ISSUE TITLE
Select calendar for which next event is displayed

### ISSUE THREAD

**Issue by theboyler** [pakerwreah/Calendr#112]
So, I love having access to my wife's calendar in Calendr, so when I want to check my availability to do something on a given day, I can see my cals and hers. But when I want to see the next event next to the menubar item, I don't need to see her next event, just those from my calendars. So, can we choose which calendars to display upcoming events, which may wells be a different list from those calendars displayed in the app when the menu item is clicked.

**Comment by pakerwreah** [comment]
That is a nice feature, I will work on that, thanks for the suggestion :)
