### ISSUE TITLE
Open native calendar app at the selected date

### ISSUE THREAD

**Issue by theboyler** [pakerwreah/Calendr#113]
I use Calendr to quickly check availability on certain dates; if I'm free, I'd like to there and then add a new event without having to go into Calendar (and if that's not possible, at the very least, if a date is selected in Calendr, when I click to open Calendar.app, it could jump to that specific date rather than just activating Calendar.app)

**Comment by pakerwreah** [comment]
I've been asked that feature multiple times, but it's not the purpose of the app. (check this other issue #111)

About opening the Calendar.app, I've tried to do that before, but Apple doesn't provide any API to navigate into the app.
The only way I could find was to use system-wide automation and that would require the user to give 4 permissions in total when they install the app, which is not great.

Again, this is not the purpose of the app and I prefer to keep it read-only.

**Comment by theboyler** [comment]
Could this applescript command not work?

`tell application "Calendar" to view calendar at (current date)` where (current date) is the actual date clicked in Calendr?

**Comment by peteschaffner** [comment]
I was also pulling my hair out trying to get this functionality in my Itsycal fork, and was able to get it working with [the undocumented `ical` URL scheme](https://github.com/peteschaffner/Itsycal/commit/b6844ffba3a440352de5fc41b871d1fc56efd224).

It's brittle but has the benefit of not requiring the extra permissions. (It also might be faster than compiling and running AppleScript 🤔.)

Anyway, sorry to comment on a closed issue, but thought I'd leave this here in case it could be useful!

**Comment by pakerwreah** [comment]
@peteschaffner That is amazing! Thank you!
I've implemented it in this [PR](https://github.com/pakerwreah/Calendr/pull/126) if you wanna have a look.
I will test it for a few days before releasing a new version.

**Comment by pakerwreah** [comment]
I've already found issues with all-day events because I didn't follow your code properly 😆

**Comment by peteschaffner** [comment]
Ah good catch! Yeah it isn't easy to follow that code… it's a mess and pretty much only makes sense to me 😄
