### ISSUE TITLE
Please add a FLASHING feature for upcoming meetings...

### ISSUE THREAD

**Issue by jlm70** [pakerwreah/Calendr#115]
It would be GREAT, really GREAT, to have a visible (LOT visible) notification of upcoming meetings.
Such as an yellow flashing in the previous 5 minutes and a RED flashing for the last minute before event starts...
Potentially even with an audible notification.

It would be quite useful...
With the pandemic and several video calls any 30 minutes... losing some coming ups is so frequent!

MANY THANKS

**Comment by pakerwreah** [comment]
You can already set up your events in the native Calendar app to show multiple alerts with exactly that behavior (5min before, at the start of event, etc...), even with sound.

Since that is a native system feature, there's no point in implementing it again in the app.

**Comment by jlm70** [comment]
I understand your reply, and i use the alerts within the native calendar.
But I’m normally using a big monitor, and “push notifications” appear small, on top right part of screen, mixed up among the tons of other notifications i normally receive. And - more - you need remembering to setup your alerts (not always a case when in many continuous calls).
It’s even the case, so often, that you SEE an upcoming mtg alert, and you leave it there, or close it, ‘cos managing another important call… and “it’s gone”. While a “flashing notifier” in the top bar… would let you keep on thinking about not losing the next one.

This is why i believe that a SPECIFIC calend(a)r notification might STAND OUT among the thousands of other notifications we daily receive.
Just my thought… but it’s common with many of my colleagues. And ok… maybe we work wauy too much… but this is another story :)))
