### ISSUE TITLE
Events not displaying in local time

### ISSUE THREAD

**Issue by mikes625** [pakerwreah/Calendr#121]
Since updating to 1.9.1 events only display in GMT instead of local time (EST for my location). This happens both when I have location services activated or not for calendar, date and time in system settings. Reboot doesn't correct it. Intel macbook air, MacOS 13.2.1.

Edited to correct EDT to EST.

**Comment by mikes625** [comment]
On further investigation, my personal calendar events are in EST and display correctly. Same for reminders. My _subscribed_ webcal calendars (e.g. kids' sports schedules) must be set in GMT. I can't find an option to change them. BTW, time zone support is ticked on in calendar settings, if that matters.

**Comment by pakerwreah** [comment]
I will add an option in the app settings to ignore time zones (old behavior)

**Comment by mikes625** [comment]
I had already reverted to version 1.9.0. It works fine for me. I wish there was a way to edit webcal subscriptions in the native calendar app, but apparently that's not an option. Thanks for your very fast responses!

**Comment by pakerwreah** [comment]
Fixed in v1.9.2.
Thanks for reporting this 🙇🏻‍♂️
