### ISSUE TITLE
Custom notification sound...

### ISSUE THREAD

**Issue by jlm70** [pakerwreah/Calendr#123]
Dear Carlos,
some time ago I suggested an update (as of below), that you replied as non useful / not in pipe.
**A way to better attract your attention about an upcoming meeting.**

--> You correctly suggested to use the normal system notification system in MacOS.

I tried. Many times.
But I’m using a big monitor, and “push notifications” appear small, on top right part of screen, mixed up among the tons of other notifications i normally receive. And - more - you need remembering to setup your alerts (not always a case when in many continuous calls).

And, last but not least, **it s IMPOSSIBLE in MacOS to setup a DIFFERENT sound for a calendar notification.**
Therefore calendar notifications blend (and "disappear") within the thousands of other notifications coming from browser and other apps.

So often you SEE an upcoming mtg alert, and you leave it there, or close it, ‘cos managing another important call… and “it’s gone”, forgotten. While a **“flashing notifier” in the top bar, with a DIFFERENT SOUND**… would let you keep on thinking about not losing the next one.

This is why i believe that a SPECIFIC calend(a)r notification might STAND OUT among the thousands of other notifications we daily receive.
Just my thought… but it’s common with many of my colleagues. And ok… maybe we work way too much… but this is another story :)))
Many thanks for your consideration and excellent work!
Gianluca

- - - - - -
It would be GREAT, really GREAT, to have a visible (LOT visible) notification of upcoming meetings.
Such as an yellow flashing in the previous 5 minutes and a RED flashing for the last minute before event starts...
Potentially even with an audible notification.

It would be quite useful...
With the pandemic and several video calls any 30 minutes... losing some coming ups is so frequent!
MANY THANKS

**Comment by pakerwreah** [comment]
Hi Gianluca,
I understand your struggle but I believe that no matter what I do, it won't solve your problem.
You need an specific app that is focused on reminding you (very intrusively) of your upcoming tasks, and that is not the purpose of Calendr.
My app is just a small calendar at the corner of the screen and I have no plans of changing that behavior.

I always try not to replicate native features that would only increase the app's complexity and maintainability.
Even if those features don't suit you 100%, they do exist.
If Apple decides to remove the native calendar notifications, then that's when I step in.
It had happened before with the date formatting. I refused a request to implement formatting inside the app but one day the customizations from system settings were simply removed from macOS. That day I went back and implemented it.
