### ISSUE TITLE
软件非常棒，但是太占用内存了，希望您解决一下，谢谢。

### ISSUE THREAD

**Issue by 1545118122** [pakerwreah/Calendr#127]
<img width="269" alt="image" src="https://user-images.githubusercontent.com/61002114/234953444-058633ec-e0e9-4042-bbdb-df3bc5f9b633.png">

**Comment by pakerwreah** [comment]
It shouldn't use that much memory. 
Please try to monitor what features you are using that causes the problem.
That's what it looks like here:
<img width="310" alt="Screenshot 2023-04-27 at 21 06 16" src="https://user-images.githubusercontent.com/803954/234979244-40e27bde-4a7d-48e0-a915-f56fb6c0cf57.png">

**Comment by pakerwreah** [comment]
I actually found a memory leak 🙂
It will be fixed in v1.9.4

The event list view models were not deallocating, so if you kept hovering the dates the memory usage would increase indefinitely.

**Comment by 1545118122** [comment]
感谢您迅速的解决了问题。祝您事事顺心
