### ISSUE TITLE
Different weekend days

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#13]
Although not my case, in some countries weekend and first day of the week are different. Is Calendr taking these settings from the system settings?

**Comment by pakerwreah** [comment]
First day of week comes from the system. 👍🏻

Weekend is always Saturday and Sunday. I know a small bunch of countries have different weekends, but I don't think it is worth cluttering the configuration panel with that (for now), as the app doesn't have a large user base. I also don't see any kind of configuration about it in the system or in the native Calendar app.

I'm just gonna wait until someone says: "Hey, I live on an island where the weekend is on Wednesday" ¯\\\_(ツ)\_/¯
