### ISSUE TITLE
Cannot set custom date

### ISSUE THREAD

**Issue by rofrol** [pakerwreah/Calendr#131]
<img width="257" alt="Screenshot 2023-05-25 at 23 36 38" src="https://github.com/pakerwreah/Calendr/assets/28787/95b5ecf7-a5e7-4cdd-8a05-a020e951e68c">

**Comment by pakerwreah** [comment]
@rofrol could you please check if this build solves the issue for you?
[Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/11578901/Calendr.app.zip)

**Comment by rofrol** [comment]
Solved
