### ISSUE TITLE
Icon in the Menu-bar

### ISSUE THREAD

**Issue by JonyChuh** [pakerwreah/Calendr#136]
If the icon of Calendr in the Menu-bar includes both week and date, it will be much better. (e.g. SAT, 22, displayed in two lines.)
Thanks for your work.

**Comment by pakerwreah** [comment]
It would be very hard to read two lines of text inside the icon, but I'm working on a version to draw the date on it.

**Comment by JonyChuh** [comment]
Thank you very much for your reply.
Actually, it is also easy to read with two lines inside the icon. You can try the app named "dato". It has several styles of the icon in the Menu-bar for you to choose, one of them is two lines of text inside the icon. This style can save the room of the Menu-bar. It presents in the most concise way, allowing you to simply look at the Menu-bar to know the date and day of the week, without needing to click on an icon. If you need to further view more content, then you would need to click on the icon.
The above is just my personal suggestion, hoping your app will get better and better, that's all.

**Comment by JonyChuh** [comment]
Here is a screenshot of the icon for that app. (Please ignore the spacing between my icons, as I have reduced the spacing in order to make the icons more compact and display more of them.Please ignore the spacing between my icons, as I have reduced the spacing in order to make the icons more compact and display more of them.)
<img width="1440" alt="iShot_2023-07-23_10 25 01" src="https://github.com/pakerwreah/Calendr/assets/138984173/13c60d09-b0dd-4b3c-983c-2acb66ad8cc8">

**Comment by pakerwreah** [comment]
That's still hard to read for me 😅, but I will see what I can do.
