### ISSUE TITLE
How to Install 

### ISSUE THREAD

**Issue by cdhamilton** [pakerwreah/Calendr#138]
Hi,

Im new to coding and github. How do i install this calendar app?

**Comment by pakerwreah** [comment]
Hi, go to releases and download the Calendar.app.zip file.
https://github.com/pakerwreah/Calendr/releases

**Comment by cdhamilton** [comment]
> Hi, go to releases and download the Calendar.app.zip file.
> https://github.com/pakerwreah/Calendr/releases

Hi, did you read my post? I understand how to download it. I don’t know how to INSTALL it.

**Comment by pakerwreah** [comment]
If you are new to GitHub you should know that you don't have to be rude to other developers. I just thought you couldn't find where to download it.

That said, just unzip the app and drag it to the Applications folder, then right click it and select "Open".
You have to do this the first time you open, because the app is not signed and macOS won't let you.
After that it will be saved as an exception and will open normally.

There a tutorial from Apple here:
https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

**Comment by cdhamilton** [comment]
> If you are new to GitHub you should know that you don't have to be rude to other developers. I just thought you couldn't find where to download it.
> 
> That said, just unzip the app and drag it to the Applications folder, then right click it and select "Open". You have to do this the first time you open, because the app is not signed and macOS won't let you. After that it will be saved as an exception and will open normally.
> 
> There a tutorial from Apple here: https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

I have downloaded the zip, I have unzipped it, but there is no app to drag. There are a lot of files, but no .app or .dmg files at all. Which file needs to be dragged?

**Comment by pakerwreah** [comment]
There should be one.
https://github.com/pakerwreah/Calendr/releases/download/v1.9.7/Calendr.app.zip
<img width="565" alt="Screenshot 2023-07-24 at 12 09 34" src="https://github.com/pakerwreah/Calendr/assets/803954/9c50aa40-7907-42f5-a486-9e84ddf17ba9">

**Comment by cdhamilton** [comment]
> There should be one. https://github.com/pakerwreah/Calendr/releases/download/v1.9.7/Calendr.app.zip <img alt="Screenshot 2023-07-24 at 12 09 34" width="565" src="https://user-images.githubusercontent.com/803954/255572441-9c50aa40-7907-42f5-a486-9e84ddf17ba9.png">

That is very strange. If i download from the link you just provided, it works. However, when I downlod from the repo it does not work.

**Comment by pakerwreah** [comment]
You are probably downloading the source files. You have to go to the "releases" page.

<img width="442" alt="Screenshot 2023-07-24 at 12 21 36" src="https://github.com/pakerwreah/Calendr/assets/803954/402a7e7b-b636-46f9-aeed-80df7cbbef02">

<img width="619" alt="Screenshot 2023-07-24 at 12 19 53" src="https://github.com/pakerwreah/Calendr/assets/803954/9d0f2225-2e27-4492-92af-9279fbf007c5">
