### ISSUE TITLE
How to install 📥 

### ISSUE THREAD

**Issue by pakerwreah** [pakerwreah/Calendr#139]
[![release](https://img.shields.io/github/v/release/pakerwreah/Calendr)](https://github.com/pakerwreah/Calendr/releases/latest)
1. Go to the releases page and download the most recent `Calendr.app.zip`.
2. Unzip the archive and drag `Calendr.app` to the `Applications` folder.
3. Right click it and select `Open`.

☝🏻 You have to do this the first time you open, because the app is not signed and macOS won't let you.
After that it will be saved as an exception and will open normally.

Here's a tutorial from Apple:
https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

**Comment by mracos** [comment]
For reference in case someone wants to install with homebrew [here is how I did it](https://github.com/mracos/homebrew-tap/blob/a5c3aca2453329c5e937d603fd0f6d73c81dacf4/Casks/calendr.rb) 😄

**Comment by mracos** [comment]
Initially it is, but it _should_ fetch latest releases [because of the `appcast` stanza on it](https://github.com/orgs/Homebrew/discussions/173) on new installs

I might try to submit a PR to [homebrew-cask](https://github.com/Homebrew/homebrew-cask) later

**Comment by mracos** [comment]
Just a FYI, [got rejected](https://github.com/Homebrew/homebrew-cask/pull/152677#issuecomment-1672506377) because the app needs to be signed which I have no idea if feasible or possible. Will keep using the one in my own tap for now 😄

Thank you so much for this little app 💙

**Comment by pakerwreah** [comment]
It surely can be signed, I just don't want to pay Apple $99 per year 😆

**Comment by mracos** [comment]
That's... understandable 🤣

What a bummer that you need to pay a subscription to sign stuff. Well, thanks for the explanation and the TIL!

**Comment by thedavidweng** [comment]
> Just a FYI, [got rejected](https://github.com/Homebrew/homebrew-cask/pull/152677#issuecomment-1672506377) because the app needs to be signed which I have no idea if feasible or possible. Will keep using the one in my own tap for now 😄仅供参考，被拒绝是因为该应用程序需要签名，我不知道这是否可行或可能。现在😄将继续使用我自己的水龙头中的那个
> 
> Thank you so much for this little app 💙非常感谢你这个小应用程序 💙

Is it possible to have a github action that automatically push the latest version to the tap?

**Comment by mracos** [comment]
> Is it possible to have a github action that automatically push the latest version to the tap?

@thedavidweng It could checks once a day and then submit a PR? Maybe something already exists on the marketplace. Feel free o contribute if you want!

Also, @pakerwreah, do you want to move this formula to a repo under your wing?

> @mracos I think you said your tap was not tied to a specific version, right? 🤔

yeah @pakerwreah, I shared a bit of fake news, my bad on that 😅
I assumed that it was not bc of the appcast stanza but it seems (at [least with livecheck](https://docs.brew.sh/Brew-Livecheck)) that we have to manually run `brew livecheck`

<img width="562" alt="Screenshot 2024-03-29 at 16 24 36" src="https://github.com/pakerwreah/Calendr/assets/14015177/b5a5916a-2cfd-4f10-9140-7cdbd2c92730">

And tbh it was not working. Fixed it, also fixed the `appcast` warning (although I thought I [fixed it a while ago](https://github.com/mracos/homebrew-tap/commit/4310ef4ddb991de223ea1a97433bec119e7d864f) but missed a dangling call), and [already updated](https://github.com/mracos/homebrew-tap/blob/f9a7fbf1c4ffdb43d24bdac7caec0d49cd81b042/Casks/calendr.rb) to the latest version!

Thanks for the heads up 🙇

**Comment by thedavidweng** [comment]
> > Is it possible to have a github action that automatically push the latest version to the tap?
> 
> @thedavidweng It could checks once a day and then submit a PR? Maybe something already exists on the marketplace. Feel free o contribute if you want!
> 
> Also, @pakerwreah, do you want to move this formula to a repo under your wing?
> 
> > @mracos I think you said your tap was not tied to a specific version, right? 🤔
> 
> yeah @pakerwreah, I shared a bit of fake news, my bad on that 😅 I assumed that it was not bc of the appcast stanza but it seems (at [least with livecheck](https://docs.brew.sh/Brew-Livecheck)) that we have to manually run `brew livecheck`
> 
> <img alt="Screenshot 2024-03-29 at 16 24 36" width="562" src="https://private-user-images.githubusercontent.com/14015177/318123789-b5a5916a-2cfd-4f10-9140-7cdbd2c92730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDE5NDEsIm5iZiI6MTcxMTc0MTY0MSwicGF0aCI6Ii8xNDAxNTE3Ny8zMTgxMjM3ODktYjVhNTkxNmEtMmNmZC00ZjEwLTkxNDAtN2NkYmQyYzkyNzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE5NDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZDA1ZGVjYTQ0YWJjZDg0MGY2NDNkNzAwNTI1OGUzNjM0MTBkMWUxZGZhNzQzYTJiYTA4YWZhOGMzMzZmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJQmS6Ug4xi_7SvIhu3ZK6uyekZ6K6cCvxIaKUANLVw">
> And tbh it was not working. Fixed it, also fixed the `appcast` warning (although I thought I [fixed it a while ago](https://github.com/mracos/homebrew-tap/commit/4310ef4ddb991de223ea1a97433bec119e7d864f) but missed a dangling call), and [already updated](https://github.com/mracos/homebrew-tap/blob/f9a7fbf1c4ffdb43d24bdac7caec0d49cd81b042/Casks/calendr.rb) to the latest version!
> 
> Thanks for the heads up 🙇

Thank you! Yes I do believe this can be done with a github action, @pakerwreah do you want to maintain your own tap?

**Comment by pakerwreah** [comment]
I don't want another thing to maintain 😅
I can see myself, in the future, losing hours trying to figure out some random homebrew breaking change.
