### ISSUE TITLE
Menu Icon not updating (seconds or minutes)

### ISSUE THREAD

**Issue by suayip-u** [pakerwreah/Calendr#141]
When using a custom layout for the date (e.g. "hh:mm:ss") minutes and seconds are not updating unless you click on the icon to open up the calendar overlay. Even then it is only updating on every click. Maybe you could consider adding an interval or something to update the icon every second or every minute.

**Comment by pakerwreah** [comment]
That's expected. 
I never had the intention to support time, since we cannot remove Apple's menu bar clock.
I will add that in `v1.10.1` if it doesn't cause any major issues.
