### ISSUE TITLE
Multidisplay Support Not Working

### ISSUE THREAD

**Issue by amangalampalli** [pakerwreah/Calendr#147]
When I use a two display setup and I open Calendr on the non-primary display, the Calendr seems to go behind the actual date.
![Screenshot 2023-09-20 at 11 46 06 PM](https://github.com/pakerwreah/Calendr/assets/25261413/e8300c45-8070-4696-86e7-2b666e6f3e56)

**Comment by pakerwreah** [comment]
Interesting... I use a two display setup and that doesn't happen.
Could you give me as much information as possible about your setup?
(Calendr version, macOS version, display resolutions, etc...)

**Comment by amangalampalli** [comment]
Alright, here's all the information I have:

macOS Version: 13.5.2
Calendr Version: 1.10.3
Display Resolutions: 16-inch (3456 × 2234), 21.5-inch (1920 × 1080)

I'm not sure what else there is, but I do notice something weird where Calendr will flash the actual calendar for a split second before repositioning it to be above the menu bar.

**Comment by pakerwreah** [comment]
Could you make a video of the issue?

Also, try this:
- Have the settings window open and do the glitch
- Now toggle the "Show week numbers" checkbox and see if the calendar goes back to the normal position

**Comment by pakerwreah** [comment]
Do you use any kind of menu bar manager, like Bartender?

**Comment by pakerwreah** [comment]
Can you check version 1.10.2 as well? I might have introduced this bug in the latest release when I was trying to fix another problem with two displays.

**Comment by pakerwreah** [comment]
Never mind, I was able to reproduce it.
It does that with certain levels of zoom in version 1.10.3.
You can change calendar the zoom in Preferences or just use 1.10.2 until I fix this.
Thanks for reporting 🙇🏻‍♂️

**Comment by amangalampalli** [comment]
Alright, apologies for the delay in responses, it's about 1:45 AM here, but glad I was able to raise it to your attention! Love the work you've done on Calendr so far!
