### ISSUE TITLE
Localization 🌎 💬 

### ISSUE THREAD

**Issue by pakerwreah** [pakerwreah/Calendr#15]
- [x] English 🇺🇸
- [x] Portuguese 🇧🇷 
- [x] French 🇫🇷

Feel free to send me your translations, including the ones already supported if you find something weird.
Please, only contribute with languages that you actually use, so I can have a better picture of the user base.

**Comment by mrdumont1** [comment]
[de.lproj.zip](https://github.com/pakerwreah/Calendr/files/8108069/de.lproj.zip)
Here you have the German translation for your great tool. Works like a charm for me.

**Comment by Svec-Tomas** [comment]
Please find attached the Slovak translation for Calendr.
[sk.lproj.zip](https://github.com/pakerwreah/Calendr/files/14795839/sk.lproj.zip)

**Comment by Svec-Tomas** [comment]
<img width="356" alt="Calendr" src="https://github.com/pakerwreah/Calendr/assets/138758322/a53b0628-9d32-4c07-9d14-b9af222a9583">

I have found these 2 strings, that were not available for translation, so they are still in English.

**Comment by pakerwreah** [comment]
All of those titles come from your system. They are the same as your native Calendar app.
I didn't find a way to rename them in macOS, so they probably come from your calendar provider.
