### ISSUE TITLE
"Please install SwiftGen"

### ISSUE THREAD

**Issue by Ashtronaut09** [pakerwreah/Calendr#151]
Hi! Beginner dev here. I love your app! I've started using it as I was looking build something like this for my first project. I'm trying to build this and it says "Please install SwiftGen." I did a podinstall of SwiftGen and also did a brew install of SwiftGen but it still is asking me to do this. I'm not sure what to do, kinda stumped. Is this something you might know how to get it to build? Thank you!

**Comment by pakerwreah** [comment]
For some reason I had swiftgen linked in my `/usr/local/bin` <sub>(probably some rushed work-related setup)</sub>
If you update your repository with the master branch it should work now.
I added Homebrew's path to the script.

If you have any other issues, feel free to ask. 😉

**Comment by Ashtronaut09** [comment]
Brilliant! Thank you, now to dig through it a bit. Just wondering, why did you use SwiftGen? I haven't heard about it before, but I assume it's just cause I'm new. It looks really useful!

**Comment by Ashtronaut09** [comment]
@pakerwreah your "buy me a coffee" link is broken btw ;)
