### ISSUE TITLE
Show Next Event Functionality Not Working in macOS Sonoma

### ISSUE THREAD

**Issue by amangalampalli** [pakerwreah/Calendr#152]
The Show Next Event functionality seems to be broken in macOS Sonoma. Even though I have an event in the next couple of hours, the Next Event doesn't show up in the menu bar even when it is set to 24-hour visibility.

**Comment by pakerwreah** [comment]
That happened to me before, even before upgrading to macOS Sonoma.
Fortunately (or maybe not), it didn't happen ever again so I don't know how to reproduce it 🔮
Just quit and reopen the app. If that happens again in the future, try to remember what you did before and please tell me.

**Comment by amangalampalli** [comment]
In this case, I've tried quitting and reopening the app multiple times, but it doesn't seem to pick up the next event I have which is in about 10 hours or so, even when set to display the next event in 24 hours. Maybe there is another problem that I can't seem to put my finger on?

**Comment by pakerwreah** [comment]
Try un/checking the clock icon in the calendar list and see if that changes something.

**Comment by amangalampalli** [comment]
Yeah, that seemed to fix it. I guess disabling reminders from showing up adds back the events. I'm assuming this is a bug of some sort?

**Comment by pakerwreah** [comment]
Probably. If you enable the reminders again, does the problem come back?

**Comment by amangalampalli** [comment]
Yeah enabling reminders again removes the next event from the menu bar. So unchecking reminders shows the event and checking the reminders makes the event disappear.

**Comment by pakerwreah** [comment]
They should both show in the menu bar. Maybe there's not enough space?

**Comment by pakerwreah** [comment]
I usually place the one with the higher priority to me on the right, so when I'm using my macbook and there's not enough space (because of the notch), the left one disappears.

![Screenshot 2023-09-28 at 09 54 56](https://github.com/pakerwreah/Calendr/assets/803954/e0d99213-c210-4252-8d5b-da609ad2d281)

**Comment by amangalampalli** [comment]
I guess the weird part of this is that I don't have any active reminders, so in theory there shouldn't be anything to display or render.

**Comment by pakerwreah** [comment]
Well... that's... so weird 😅

**Comment by pakerwreah** [comment]
Are you using the checkbox, to completely disable the reminder, or the clock/moon icon?
What's the effect when you toggle each one?

**Comment by amangalampalli** [comment]
So using the checkbox to completely disable the reminders and the clicking on the clock turning it into a moon, both result in the next event showing up. If the clock icon is there or reminders is checked, the event doesn't show up anymore.

**Comment by amangalampalli** [comment]
Yeah, I'll give this a try in the morning, it's about 2 AM here, will completely uninstall with AppCleaner (to purge the config files) and then will try again.

**Comment by amangalampalli** [comment]
Yup this seemed to fix it. I'm confused which specific config file might have been corrupted, but redownloading the app, and enabling the "Shorten if notch present" feature seemed to have fixed it for now.

**Comment by pakerwreah** [comment]
Well, I'm glad that it got solved in the end. 
It's very hard to know what was going on without being able to look into the data.
It can be that the upgrade to macOS Sonoma messed up the calendar IDs in your user preferences. 🤷🏻‍♂️
If that happens again, feel free to open a new issue and we can investigate it further.
