### ISSUE TITLE
Remove blank next event items from menu bar

### ISSUE THREAD

**Issue by nguyentranbao-ct** [pakerwreah/Calendr#153]
Hi, I have noticed that there are two blank menu items when there is no next event. Can you remove them? Sure that I can move them to the left so they are completely invisible. But removing them is just so much better.

![image](https://github.com/pakerwreah/Calendr/assets/99800845/7b2b6be3-b4d5-41b3-b041-45a1928329a0)

Thank you for this amazing tool.

**Comment by pakerwreah** [comment]
Unfortunately, I can't. 😞

If I remove them, the system forgets where they were, so when I show your next events again they will show up as the last item on the left of your menu bar.

That's very annoying and frustrating, but I still couldn't find a way to work around this behavior.

**Comment by nguyentranbao-ct** [comment]
Yup, it looks so nice now. Thank you so much. 💯💯
