### ISSUE TITLE
Suggestion - skip event in menu bar

### ISSUE THREAD

**Issue by theboyler** [pakerwreah/Calendr#156]
Use case: I have events in my calendar that aren't 'real' events; they might be more like reminders (because reminders.app just doesn't work for me) or be events I need to be aware of, but no necessarily be reminded of. For example, we have a cleaner who visits every week for an hour, and I use my calendar as the base for GCal booking system, so the visit of the cleaner is an event each week so I don't get a booking for a meeting when I won't be in position to meet with anyone. However, I don't need to know that in 1 hour, the cleaners are coming. So, when I click an item in the menu bar and see the details of the event, the ability to 'skip' this event and move to show the next event would be really great.

**Comment by pakerwreah** [comment]
I see your point. I also have that problem when I finish a meeting earlier but it has like 30 minutes left, it stays in the menu bar catching my attention. I will definitely work on that.

**Comment by theboyler** [comment]
That's a great use case - that happens all the time!

**Comment by theboyler** [comment]
Hi Carlos - is this working in the latest version for you? It seems to have disappeared as an option in 1.10.8

**Comment by pakerwreah** [comment]
It works fine for me 🤔

**Comment by theboyler** [comment]
![Screenshot 2024-02-20 at 14 19 25](https://github.com/pakerwreah/Calendr/assets/10658426/4c16461d-b334-4c76-8add-d31e1b7f2cd6)

There's no option to click to dismiss this event...

**Comment by pakerwreah** [comment]
Right click it

**Comment by theboyler** [comment]
* slaps forehead *

**Comment by untitled500** [comment]
Suggestion for discoverability: Add the Skip / Dismiss option within the popup, instead of needing a right click.
