### ISSUE TITLE
Issue: no current events and reminders shown on the menu bar

### ISSUE THREAD

**Issue by GniqUil67** [pakerwreah/Calendr#159]
Hi, It seems like there is an issue with my calendr. I downloaded the latest version on my MacBook Air and iMac 2019. None of current events or reminders are showing up on the menu bar of my iMac 2019, and the current reminders are not displaying on the menu bar of my MacBook Air. Thanks.

**Comment by pakerwreah** [comment]
Please inform your macOS version.
Check if Calendr has full access to your Calendars and Reminders in Privacy and Security.
Double check if you enabled Next Event in the app Preferences.
Also check if you have ticked the calendars you want to see in the app and if they have the clock icon (not the moon with zzz) in front of their names.

<img valign=top width=300 src='https://github.com/pakerwreah/Calendr/assets/803954/f91ef03c-297e-42bc-9efa-2751d74805f0' />
<img valign=top width=250 src='https://github.com/pakerwreah/Calendr/assets/803954/ff3e9c39-529f-4a29-b0ab-0f2feec7f025' />
<img valign=top width=200 src='https://github.com/pakerwreah/Calendr/assets/803954/4ee9901b-c4ea-44a6-ab8c-fb2fc77ba734' />

**Comment by GniqUil67** [comment]
Thanks so much for helping me out. They all work now.

Carlos Enumo ***@***.***> 于2023年11月30日周四 17:31写道：
