### ISSUE TITLE
Add shortcut to show/hide (e.g. Option + C, ⌥ + C)

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [pakerwreah/Calendr#160]
Amazing app! Could it be possible to implement a shortcut to show/hide the dropdown with the calendar?

**Comment by 0xAdriaTorralba** [comment]
I don't think it would be too much of a hassle. 

AFAIK, there are already open-source libraries that handle this, however, not all of them support any arbitrary combination of keys as a shortcut (e.g. in some cases, assigning Option + <key> alone is not possible, it needs to assign another modifier in order to work).

**Comment by pakerwreah** [comment]
Hey, could you give it a try?
https://github.com/pakerwreah/Calendr/releases/tag/v1.10.8

**Comment by 0xAdriaTorralba** [comment]
It works great!
