### ISSUE TITLE
Don't see anything in menu bar when opening Calendr

### ISSUE THREAD

**Issue by allansolutions** [pakerwreah/Calendr#162]
I have installed Calendr per the instructions here https://github.com/pakerwreah/Calendr/issues/139

I can open Calendr and see it running in Activity Monitor. But I don't see anything on my menu bar or anything in my UI related to Calendr.

I don't normally use the Apple Calendar, rather Google. I have just imported my Google Calendar into Apple Calendar and all is looking good there. I wonder if there's anything else I need to do, or if the issue is unrelated to this

**Comment by pakerwreah** [comment]
Even if you have no calendars, it should at least show the date.
Are you using a macbook with notch? If you have too many items, it might be hidden.

You can also try launching the app and hitting `cmd + ,` to open the preferences window, and try to toggle the visibility.

As a last resort you can try to kill the app, remove this file and open it again:
`~/Library/Containers/br.paker.Calendr/Data/Library/Preferences/br.paker.Calendr.plist`
❗If you do that, please save the file first and upload it here so I can see what caused the issue.
