### ISSUE TITLE
notarization

### ISSUE THREAD

**Issue by swallytel** [pakerwreah/Calendr#163]
Seems like a good app, it's a shame it's not notarized. Do you plan on doing this so that it passes the macOS Gatekeeper check and gains more adoption?

<img width="261" alt="Screenshot 2024-02-16 at 11 15 27 PM" src="https://github.com/pakerwreah/Calendr/assets/159210637/691cebc2-ffa5-4cfb-b1ed-aa68be2efc6b">

**Comment by pakerwreah** [comment]
That would cost me $99 a year and I don't get any revenue out of it. So unfortunately that's not in my plans.
