### ISSUE TITLE
Minor Quality-of-life feature requests

### ISSUE THREAD

**Issue by untitled500** [pakerwreah/Calendr#168]
1. An outline around a month (like Itsycal does - screenshot below)
2. Some hint text within settings to tell people where to set day when a week starts on. Bonus if there is a button to take me there.
3. IMO, since when I click to select a date then the calendar for that date is displayed - then we do not need the same thing to happen when hovering over dates in the calendar.
4. Next event length is too small. For me each step seems to add 4 extra characters. I'd prefer either a bigger step, or ability to make it longer than it does.

<img width="399" alt="image" src="https://github.com/pakerwreah/Calendr/assets/59500937/a2076850-be02-443b-a848-f51f9566baea">

**Comment by pakerwreah** [comment]
1. That will remain an Itsycal feature for now

I will see what I can do for the other suggestions

**Comment by untitled500** [comment]
Thanks! I think no.1 is the most value adding though: makes it a lot easier to see where I am in the month. I don't want to sound pretentious here, but do you mind sharing the rationale why you do not want to implement it?

**Comment by pakerwreah** [comment]
I don't want to implement cosmetic features to make it look like another app.
I also don't have time to do it, but I accept PRs if you feel like implementing it.

**Comment by austinarchibald** [comment]
Just installed with [Stats](https://github.com/exelban/) to replace iStat Menus. Another suggestion: Option to put day of the month within the Calendar icon. Helps to consolidate information, my menubar real estate is precious with this notch. I like how iStat does it (below), though it's just a square. Also is there a website that shows all the Date and Time format code you're using? Having trouble making it look exactly as I want it.

<img width="115" alt="image" src="https://github.com/pakerwreah/Calendr/assets/12240843/52bc68d2-4b3d-4fb5-ae17-723ba3f2a42a">

**Comment by pakerwreah** [comment]
@austinarchibald I'm glad you were able to sort it out :)
