### ISSUE TITLE
Spanish localisation

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#17]
Hi, please create a folder for Spanish localisation in the resources so I can do the translation without having to install Xcode 😊

**Comment by pakerwreah** [comment]
You can open it with any text editor
Calendr/Assets/en.lproj/Localizable.strings

**Comment by gferreroferri** [comment]
OK. can I create the es.lproj directory as well?

**Comment by pakerwreah** [comment]
Yes

**Comment by gferreroferri** [comment]
Done 😊 However, I have a question: why the names of the months appear in English even my regional settings are set to Spanish?

**Comment by pakerwreah** [comment]
Probably a bug, I'll take a look.

**Comment by pakerwreah** [comment]
It's working fine for me. I think although you have your region set to Spanish, your language is not.

**Comment by gferreroferri** [comment]
Yes, my language is set to Spanish. See the screenshot with the name of the month as shown in Calendr and my settings
<img width="773" alt="Captura de pantalla 2021-02-23 a las 9 17 08" src="https://user-images.githubusercontent.com/823394/108812590-10ba2900-75b8-11eb-8b42-3b854cbca01a.png">

**Comment by gferreroferri** [comment]
Forget this, after the Spanish localisation is done, now it shows correctly 😊
