### ISSUE TITLE
Add option to move Control Center button

### ISSUE THREAD

**Issue by marekmasek** [pakerwreah/Calendr#170]
Do you think it would be possible to add an option to move the system Control Center icon in menu bar to the left?
I would like to have Calendr right next to the time...

Currently it's possible to have it only like this:
<img width="264" alt="image" src="https://github.com/pakerwreah/Calendr/assets/48589322/74bc65af-1470-4dcf-aa1d-56a1e160f6ac">
I would like to get something like this:
<img width="260" alt="image" src="https://github.com/pakerwreah/Calendr/assets/48589322/46140566-7abb-41af-a75f-48d18523d721">

**Comment by pakerwreah** [comment]
That would be great, but unfortunately that's locked in place by Apple, so there's nothing I can do about it.
