### ISSUE TITLE
Make birthday icon optional

### ISSUE THREAD

**Issue by wzxu** [pakerwreah/Calendr#171]
Hello. First of all thanks for this app. I do use Fantastical but have been looking for a simpler alternative. This looks great.

I noticed this gift icon in front of the menubar control, with no explanation or setting found. At first I thought it's a reminder for donation 😂 After a while I realized it's an indicator for birthday when I found [this issue that introduced it](https://github.com/pakerwreah/Calendr/issues/18).
<img width="55" alt="95291" src="https://github.com/pakerwreah/Calendr/assets/5619348/33df248a-037b-4f69-bcee-0af2cf9dc1dc">

Personally for me, I think it's unneeded clutter, especially if I want to have icon only like the above picture (but I'd still like to see birthdays when I expand the popover). I think it would be great if there could be an option, e.g. "Show birthday icon" in this "Menu Bar" section so it could be turned off. It makes sense for it to have a setting too since all the other elements such as icon and date do. 
<img width="272" alt="38426" src="https://github.com/pakerwreah/Calendr/assets/5619348/3bb28022-6071-44d2-bf84-57a68ffb72be">

Thanks!

**Comment by pakerwreah** [comment]
Hello! 👋🏻 
it's not a veeery intuitive way to do it, but you can disable it in your birthday calendar, by ticking the clock icon (turn it into a moon)

![Screenshot 2024-04-06 at 23 34 53](https://github.com/pakerwreah/Calendr/assets/803954/ad3a8fc1-9658-4d81-9a35-478825217f84)

I did it that way, because maybe you wanna know when someone in your family is having birthday, but don't care about birthdays in your company's calendar, for example. That way you can have more granularity over it.

**Comment by wzxu** [comment]
@pakerwreah Ah that's a nice use case I didn't think of. Thanks. 
Where can I find the clock icon, by the way? I'm not seeing it in Calendr, or even the Apple Calendar app?
<img width="340" alt="1998" src="https://github.com/pakerwreah/Calendr/assets/5619348/40fea9e4-fc02-4c8c-ad8c-4a519cd6389c">

**Comment by pakerwreah** [comment]
It should be exactly there (on the right) 👀
I have no idea why it's not showing for you.

**Comment by wzxu** [comment]
> It should be exactly there (on the right) 👀 I have no idea why it's not showing for you.

Huh that's weird. Double checked and I'm on the latest version so it should be the same as yours. 
Wonder what the reason is… 🤔

**Comment by pakerwreah** [comment]
what macOS version are you in?

**Comment by pakerwreah** [comment]
Try to see if the button is there and just invisible, for some reason.

<video src='https://github.com/pakerwreah/Calendr/assets/803954/bf696097-b4a4-4d4b-aa11-4961d0da13e5'></video>

<sub>(the cursor doesn't flicker that way, only in the video)</sub>

**Comment by pakerwreah** [comment]
ohhhh nvm... you have the "Show next event" option unticked 🤦🏻‍♂️

**Comment by wzxu** [comment]
> ohhhh nvm... you have the "Show next event" option unticked 🤦🏻‍♂️

This is it! After ticking it the clock icon shows up. 
I can toggle it and afterwards the setting remained even if I untick "show next event" again.

**Comment by pakerwreah** [comment]
Fixed in [v1.10.10](https://github.com/pakerwreah/Calendr/releases/tag/v1.10.10) 🚀
