### ISSUE TITLE
Time convention not working in the events list

### ISSUE THREAD

**Issue by Stapxs** [pakerwreah/Calendr#172]
PS：I'm not good at English. The following content comes from the translation program.

Hello. First of all thanks for this app. Here is a suggestion from personal habits.

I am used to using the 12-hour system to check the time, but the schedule time displayed by Calendar seems to be fixed at 24 hours; maybe Calendar can automatically synchronize the settings of the system or provide relevant options?

**Comment by pakerwreah** [comment]
You can do that by using lowercase `h` and `a` in the custom date format, like `hh:mm a` = `01:15 PM`

**Comment by pakerwreah** [comment]
Sorry, maybe I misunderstood your problem.
For the other times shown in the app, like event list and event details, it should be already synching with your Language and Region settings from macOS.

**Comment by pakerwreah** [comment]
Ok, it's not working in the events list, only inside event details. I will have to look into it.
