### ISSUE TITLE
Request: Missing preview for [configurable X]  days in the list

### ISSUE THREAD

**Issue by Fischmuetze** [pakerwreah/Calendr#173]
Hi, thank you! 
I'm missing preview for [configurable X]  days in the list. I know I can hover for a day to see the events of that, but for a quick overview a preview would be nicer

**Comment by pakerwreah** [comment]
Sounds like a good idea, but that would require a big change for the tiny convenience of not having to move your mouse.
It's not what the app was designed for.
I might rethink this in the future, but I have no plans of implementing it for now.

ps.: you can record a shortcut to open the calendar and use the arrow keys in your keyboard to navigate the dates, that way you don't even have to touch your mouse.

**Comment by Fischmuetze** [comment]
ok I see, but in this case I'll switch back to Itsycal for the moment which is in the most senses absolutely  identical but have this kind of preview list. Thank you anyway for all your effort.
