### ISSUE TITLE
Request: Integration of Homebrew 

### ISSUE THREAD

**Issue by Fischmuetze** [pakerwreah/Calendr#174]
Would be great to have this app in the Homebrew repositories. Would be help to keep it automaticaly updated

**Comment by pakerwreah** [comment]
The app needs to be signed to live in the official repo, and I have no plans on doing that 💸, but you can install the cask.
See this [thread](https://github.com/pakerwreah/Calendr/issues/139) about it.
I believe you have to run `brew livecheck —tap mracos/tap` though to get the latest version.
