### ISSUE TITLE
Close an open popover when menu item is clicked again

### ISSUE THREAD

**Issue by PuzzledUser** [pakerwreah/Calendr#181]
Your excellent app behaves differently to other Apple default menubar items. Please make your popover _close_ if the menu item is clicked (again) whilst the popover is open.

Currently I have to click elsewhere to close the popover (or press ESC).

**Comment by pakerwreah** [comment]
There you go 😛
[Calendr.zip](https://github.com/pakerwreah/Calendr/files/15150541/Calendr.zip)

**Comment by PuzzledUser** [comment]
You're on fire! 🔥
Now where is your coffee tip jar?

**Comment by PuzzledUser** [comment]
You're gonna hate me for this, but your menu item transient highlight doesn't match the behaviour of other items. 

We're down in the weeds now — but if you wanted consistency, you might keep the active menu item highlight active whilst its popover is active. 🍒🔝

**Comment by PuzzledUser** [comment]
https://buymeacoffee.com/pakerwreah/c/9377177 ☕️
