### ISSUE TITLE
Events with remaining time not getting shown on more than one display

### ISSUE THREAD

**Issue by christianblessing-me** [pakerwreah/Calendr#182]
I've noticed that when there's an event (e.g. Zoom call) with a remaining time being present in the menubar, the item is only shown on one (the display currently in focus) display. When switching focus the item is blank on the display not in focus.

**Comment by pakerwreah** [comment]
Yes, that's known issue, because I'm adding the view outside of the menu bar button to avoid having huge margins around it. The native button also interferes with my click actions.
Anyway, that's expected until I find a better way to do this.
