### ISSUE TITLE
Different font being used for next event

### ISSUE THREAD

**Issue by RomainCscn** [pakerwreah/Calendr#188]
Hello,

Would it be possible to use the standard font for the next event text? 

It looks very tight and different from the font used in the menu bar.

Here's a side by side using the same text:

![CleanShot 2024-06-08 at 08 34 42@2x](https://github.com/pakerwreah/Calendr/assets/6696530/7712dbba-762f-4d9d-a817-5dc261d15d73)

---

Nevertheless, amazing app, thanks for the work.

**Comment by pakerwreah** [comment]
The idea was to make it as compact as possible, because of the limited space in the menu bar.
I will add a font size configuration to the app settings.

**Comment by RomainCscn** [comment]
Amazing, thank you for how quickly you implemented and released this!
