### ISSUE TITLE
Filter out events without a location/meeting link value

### ISSUE THREAD

**Issue by ajayjohn** [pakerwreah/Calendr#194]
Would it be possible to add an option to filter out events without a location/meeting link value from showing up in the menu bar?

This will help users like me who block time on the calendar as 'Focus Time' but really only want to checking which meeting is coming up next in the menu bar.

**Comment by pakerwreah** [comment]
That can be quite "dangerous" in my opinion.
I have had meetings where my manager simply forgot to add the link.

I would suggest you to use the `"Skip"` feature.
I think that can achieve your goal without compromises.
Left Click | Right Click
--|--
<img height=200 src='https://github.com/pakerwreah/Calendr/assets/803954/94a742cd-5df0-4556-a94a-7c546b9d2128' />|<img height=200 src='https://github.com/pakerwreah/Calendr/assets/803954/33b9b88d-44bb-4c80-b9fb-5d80c97cf56d' />
