### ISSUE TITLE
how to display the time in the menu bar

### ISSUE THREAD

**Issue by starsea** [pakerwreah/Calendr#195]
hi

I would like to be able to display the time in the menu bar.
currently only the date can be displayed.
I wish can display the time and set timezone.

**Comment by pakerwreah** [comment]
You can choose any custom format you want

<img width=300 src='https://github.com/pakerwreah/Calendr/assets/803954/8d99dc35-0dd4-47b8-9ef4-01d2a7c5e9d4' />

**Comment by starsea** [comment]
> You can choose any custom format you want
> 
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/803954/338893595-8d99dc35-0dd4-47b8-9ef4-01d2a7c5e9d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTQ5NzUsIm5iZiI6MTcxODIxNDY3NSwicGF0aCI6Ii84MDM5NTQvMzM4ODkzNTk1LThkOTlkYzM1LTBkZDQtNDdiOC05ZWY0LTAxZDJhN2M1ZTlkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNzUxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmExMjAyYmViODBiMjQyMjM3NjM5YThjZTRiYzc2NGFiZmY4NDVmNjAyOWI5M2E5MmNlMWVjN2M5YTNiMTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XpCCLHEZwKqy_fQkzxoWZ-ujL1o24Qs8drVLzfXbX48">

i see, but i wish i can format it by custom timezone,

for example, my system timezone is PDT time, i with this app can format it use UTC+8 time.  How can i  do?

**Comment by pakerwreah** [comment]
I'm afraid that's not possible.
