### ISSUE TITLE
Reminders lists should be displayed by default/Template lists Visibility Issue

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#200]
- New Reminders lists are disabled by default in the view settings. Maybe you could consider enabling them by default, instead of requiring the user to manually enable them every time they create a new list in Reminders. (One could easily forget to do this.)
<img width="219" alt="Screenshot 2024-06-27 alle 15 09 12" src="https://github.com/pakerwreah/Calendr/assets/16544166/d362eb2e-884b-4098-bb67-ae07af3275b4">

**Comment by pakerwreah** [comment]
The way I implemented this makes it difficult to refactor.
I agree that it would be nice, but it's not a huge issue.

**Comment by ilMagnifico** [comment]
I’d like to report a small issue with the Reminders app regarding the use of templates.

When creating a new template, it doesn’t automatically appear unless manually enabled. This makes it cumbersome for users, especially those who create reminders on the fly. For users unfamiliar with this extra step, it can be confusing and complicates a basic function. Additionally, it significantly limits the usability of templates, as users would need to manually enable visibility each time.

It would be great if there were an option to automatically display newly created templates to improve the user experience.

Thank you for considering this improvement!

https://support.apple.com/it-it/guide/reminders/remn29caf6e1/mac

**Comment by ilMagnifico** [comment]
I believe the default behavior should be to automatically display newly created templates, as it’s reasonable to assume that once a user creates a list, they want to use it immediately. The option to hide it should be a manual step, not a requirement, simplifying the user experience.
