### ISSUE TITLE
Calendr view may wider

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#201]
> A larger window when clicking on the calendar view.

I asked this because when you have many events from different lists in a day, the small colored dots can be more of a distraction than a helpful feature. At least for me, it’s difficult to understand what kinds of events are on a particular day since they’re all so clustered together.
<img width="251" alt="Screenshot 2024-06-27 alle 15 12 57" src="https://github.com/pakerwreah/Calendr/assets/16544166/d4af071b-f3dc-4756-a4c1-e028b33e1fb3">

**Comment by pakerwreah** [comment]
Well, probably this app is not the best one for your use-case.
I would suggest you to toggle off calendars that are not that important to you.

**Comment by ilMagnifico** [comment]
> Well, probably this app is not the best one for your use-case. I would suggest you to toggle off calendars that are not that important to you.

:(
Come on. :(
In the end, you could simply increase the option to make it more widespread. It’s a feature that I’m sure many others would find useful, not just myself.

<img width="357" alt="Screenshot 2024-06-27 alle 15 32 38" src="https://github.com/pakerwreah/Calendr/assets/16544166/c611a04d-aa26-491e-8bd0-d1b684ebfd71">

**Comment by pakerwreah** [comment]
Again, that's your specific use case.

I really don't think this is the best app if you need to keep track of 6 calendars, all of them with events, almost every day.

You need a bigger interface, and at this point you might as well just use the native Calendar app or something else like Fantastical.
