### ISSUE TITLE
brew installer

### ISSUE THREAD

**Issue by vvchik** [pakerwreah/Calendr#213]
Could you please create a brew cask for your app? 
https://docs.brew.sh/Adding-Software-to-Homebrew#casks

**Comment by pakerwreah** [comment]
hey @vvchik 👋🏻 
it is now available via my own cask.

Check the instructions here:

[![homebrew](https://img.shields.io/badge/Homebrew-gray?logo=homebrew&logoColor=FBB040)](https://github.com/pakerwreah/Calendr/issues/217)

**Comment by vvchik** [comment]
Awesome! Thank you!
