### ISSUE TITLE
Time zone issues with CalDAV subscribed calendars

### ISSUE THREAD

**Issue by maxens-git** [pakerwreah/Calendr#233]
Time problem.

Hello I have a problem about the time, indeed my events in my calendar are displayed in UTC time, and there is no way to change it. Do you have an idea to change the time zone of the application
<img width="175" alt="Capture d’écran 2024-09-09 à 20 40 49" src="https://github.com/user-attachments/assets/9d993de3-af73-463e-ba5c-4ea6e5e7850e">

**Comment by pakerwreah** [comment]
The (???) part is displayed for meetings when the event timezone is different from your system, but the time you see is actually your local time.

This is just so you know that whoever created the meeting is in a different timezone than yours.

For example, when I go to Brazil I usually see (GMT-3), but the event is displayed in local time.

**Comment by maxens-git** [comment]
There is a two hour time lag between Apple's calendar app and Calendr.

**Comment by pakerwreah** [comment]
Check if you have this enabled in Apple's calendar.

<img width=400 src='https://github.com/user-attachments/assets/fa8d63a9-4ada-4b5a-bb9a-7657d9128176' />

**Comment by maxens-git** [comment]
it was not activated, but that does not change anything, I specify that the events were created in the same time zone as where I am

**Comment by maxens-git** [comment]
I found a solution, I am subscribed to an ics calendar, and I am connected to a caldav account to have the events on my mac, but if I subscribe directly from the calendar application on macOS, this is no longer a problem

**Comment by pakerwreah** [comment]
I explicitly disabled timezone for subscribed calendars on version `v1.9.2`.
That's because I had the same setup as you. I had a subscribed calendar on Google and was synching it with my mac, but I was getting the wrong timezone.

Google probably does the conversion before reaching Apple's calendar, but still returns UTC, so Calendr was doing the conversion 2x. It's pretty unreliable. There are tons of issues around regarding subscribed calendars.

Is that a public (ics) calendar that you could share with me?

**Comment by pakerwreah** [comment]
I think I found the issue:
- I was only ignoring the timezone for `"subscribed"` calendars, but you were using a subscription from `calDAV`, which is called `"delegated"` calendar.
- This type of calendar returns `false` for `isSubscribed` in the code. I have to also check for `isDelegate`, which is only available on macOS 13. 🫠

I did some changes to check that if we can, feel free to try it out with your previously setup and please, tell me if it worked. 🙏🏻 

[Calendr.zip](https://github.com/user-attachments/files/16937672/Calendr.zip)

**Comment by maxens-git** [comment]
Thanks, I will test this tonight
