### ISSUE TITLE
Next Event is not showing in menu bar

### ISSUE THREAD

**Issue by amangalampalli** [pakerwreah/Calendr#234]
I'm currently using Calendr however, I can't seem to get the next event to display. I have events all the time and none of them show up in the menu bar anymore. Any fixes?

![Screenshot 2024-09-09 at 11 50 11 AM](https://github.com/user-attachments/assets/816a2760-b3c0-4a93-b473-46407c1446ae)
![Screenshot 2024-09-09 at 11 51 54 AM](https://github.com/user-attachments/assets/9305d21f-7af0-447a-8a3c-db12be63f2bd)
![Screenshot 2024-09-09 at 11 52 36 AM](https://github.com/user-attachments/assets/2fffd82c-b3a7-461d-b752-4268a66afafe)

**Comment by pakerwreah** [comment]
Do have the clock icon in your calendars? or the moon icon?

**Comment by amangalampalli** [comment]
Yeah, all of them seem to have the moon icon. Does this mean they are silenced? What does the clock icon mean?

**Comment by pakerwreah** [comment]
Yes, they are silenced, you can click the icon to change it.

**Comment by amangalampalli** [comment]
I've changed them all to clocks and it works now, thank you!

**Comment by pakerwreah** [comment]
New added calendars are silenced by default, but on an initial installation they should all be enabled.

That's to avoid new accounts from hijacking the next even view and making you lose your important meeting 😅 (trust me, that happened)

I'm pretty sure I have unit tests for that, but I will double check 🤔

**Comment by amangalampalli** [comment]
Yeah, I think I had updated Calendr recently and it seemed to have silenced all my pre-existing calendars by default. But the ability to snooze specific non-important calendars is really useful!
