### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by Svec-Tomas** [pakerwreah/Calendr#241]
I downloaded the Localizable.strings file to verify if any new strings were added after the implementation of the new update feature. I was unable to locate them. Is there possibly a different file containing these strings?

If so, please let me know the location so I can prepare the translation file for those strings.

I have attached a screenshot highlighting some of the areas where these new strings currently need to be translated.

![Calendr 01](https://github.com/user-attachments/assets/b1a88f36-dcef-497d-8a19-512011eb9f96)
![Calendr 02](https://github.com/user-attachments/assets/6a89a057-0eb4-4fe6-a403-f91d7db1a3d6)

**Comment by pakerwreah** [comment]
You need to copy the keys from the English file. I don't always translate everything because that would be a nightmare.

**Comment by Svec-Tomas** [comment]
Thank you for letting me know. I wasn't aware of this before, but I'll keep it in mind for the future. I've added the strings and translated them. Please find the attached translation file.
[Calendr SK.zip](https://github.com/user-attachments/files/17081873/Calendr.SK.zip)

**Comment by pakerwreah** [comment]
Thanks! I'll make sure to add them on the next version. 🙇🏻‍♂️ 
I will probably ask you for a couple more texts later.
I'm working on some accessibility features and I will add more configurations to the Preferences window.
