### ISSUE TITLE
String translated in file, but not in app

### ISSUE THREAD

**Issue by Svec-Tomas** [pakerwreah/Calendr#243]
Thank you for implementing the translations I've made. In the latest release, the phrase 'Shorten if 'notch' is present' appears in English. It was translated in a previous version, but it's now back in English. All other translations seem to be correct. Thank you very much!
![Calendar 1](https://github.com/user-attachments/assets/c0512e7d-20a0-439b-a759-5a6b81642133)
![Calendar 2](https://github.com/user-attachments/assets/e647a8bd-d5b3-41d6-97f6-3610aebb4ca4)

**Comment by pakerwreah** [comment]
Should be fixed in [v1.13.1](https://github.com/pakerwreah/Calendr/releases/tag/v1.13.1)
The "detect notch" one was broken for all languages, but French had a few more 🙈
Thanks for reporting quickly 🙇🏻‍♂️

**Comment by pakerwreah** [comment]
The project now has an auto-generated [MISSING_TRANSLATIONS.md](https://github.com/pakerwreah/Calendr/blob/master/MISSING_TRANSLATIONS.md) with links to the respective language files. They already have all the missing keys commented `//` so you can easily edit them. 🙂
