### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by Svec-Tomas** [pakerwreah/Calendr#247]
I reviewed both the English and Slovak strings but couldn't find the highlighted text that needs translation.
![Calendr 00](https://github.com/user-attachments/assets/40c22976-e016-4bc9-8fe9-2797fd510169)

**Comment by pakerwreah** [comment]
That comes from the system, I don't think we can replace it, for security reasons.

**Comment by pakerwreah** [comment]
Sorry, that's missing localization. It's in `AutoUpdater.swift` if you wanna give it a shot, otherwise I will work on that later.
Or just send me the translations here.

**Comment by Svec-Tomas** [comment]
Please don't change anything => Prosím, nič nemeň
Confirm the app location so we have permission to replace it => Potvrď umiestnenie aplikácie pre povolenie ju nahradiť
Install => Inštalovať
