### ISSUE TITLE
Calendar is slow to open when opening from menu bar icon

### ISSUE THREAD

**Issue by laurentNoudohounsi** [pakerwreah/Calendr#257]
Hi @pakerwreah 

Thanks for the great app. I was looking for an alternative to Itsycal that displayed calendar event AND reminders with a nice UI.
It's really great to use your app but I noticed a slight delay between the moment I click on the menu bar icon and the displaying of the calendar.
On the other side, opening a calendar with Itsycal is immediately

Is it something known ? 
I guess some time consuming code may running when we open the calendar.
Are we loading all the event and reminder when we click on the menu bar icon ?

Maybe I could help on it.

Thanks

**Comment by laurentNoudohounsi** [comment]
Quick Update:
After testing again Istycal and Calendar, it seems that the feeling of immediate opening comes from the fact Itscal show the calendar when the mouse click is down. Calendar trigger the even when the mouse is up.

https://github.com/pakerwreah/Calendr/blob/15bc7bd50aa91cc732289d147a0d481c32fe961c/Calendr/Main/MainViewController.swift#L854-L861

A quick fix to improve the user experience could be to simply replace `.leftMouseUp` / `. rightMouseUp` with `.leftMouseDown` / `. rightMouseDown`.

What do you think about it @pakerwreah ?

**Comment by pakerwreah** [comment]
That makes sense.

Feel free to open a PR. It looks pretty simple.

I'm on holidays right now, but I can have a look next week.

**Comment by laurentNoudohounsi** [comment]
Thanks @pakerwreah . 
The PR is here: https://github.com/pakerwreah/Calendr/pull/259 ;)
