### ISSUE TITLE
Show when an Event or Reminder is a recurrent one

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#262]
<img width="550" alt="Screenshot 2024-10-10 alle 11 39 58" src="https://github.com/user-attachments/assets/d8f4e44a-fd88-4368-a968-943f11b7369f">

Would be nice to have the 🔁 symbol near the Event/Reminder to specify that is something recurrent.

**Comment by pakerwreah** [comment]
I have mixed feelings about this, because 99% of my events are recurrent.
It makes sense for tasks/reminders, but not so much for events.

**Comment by ilMagnifico** [comment]
> I have mixed feelings about this, because 99% of my events are recurrent. It makes sense for tasks/reminders, but not so much for events.

Almost the same, but it's important for Me to know if that is a recurrent event or just a unique one.

At least give us the possibility, may be useful for others, since it's an open source software.

**Comment by pakerwreah** [comment]
Sure thing, I'm just brainstorming.
I'm gonna add a config to select if you want to show the recurrence indicator for `Reminders`, `Events` or `Both`.

**Comment by pakerwreah** [comment]
I went for the easiest path which is just showing/hiding it everywhere.
Life is too short to create granular options 😂

**Comment by pakerwreah** [comment]
btw, I was going to show the recurrence description in the event popup, but Apple is a bitch and doesn't give me the rules for detached events, so I gave up.

I found hacky ways where you have to split the event ID and search the whole year for an event that starts with that, and hopefully find something. It's a nightmare, performance-wise terrible, and probably only works with google calendar.
