### ISSUE TITLE
Updated Slovak translation

### ISSUE THREAD

**Issue by Svec-Tomas** [pakerwreah/Calendr#263]
Please find attached updated Slovak translation.
[Calendr.zip](https://github.com/user-attachments/files/17367090/Calendr.zip)

**Comment by pakerwreah** [comment]
Could you open a PR?
You can edit the file directly on Github.

[MISSING_TRANSLATIONS.md](https://github.com/pakerwreah/Calendr/blob/master/MISSING_TRANSLATIONS.md)

Please keep the existing structure, just change the texts and remove the `//`.

**Comment by Svec-Tomas** [comment]
I was not aware that I could edit the file directly on GitHub. Please check if I did everything correctly.

**Comment by pakerwreah** [comment]
Perfect 👌🏻
