### ISSUE TITLE
Bithdays not having dots in month view

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#265]
Month view
<img width="338" alt="Screenshot 2024-10-20 alle 11 10 37" src="https://github.com/user-attachments/assets/f52949f0-8fbc-4c1c-ba16-7b78b558105a">

What's the point of having a dot in the month view (which occupies space) for saying that somebody that day will to celebrate one's birthday.
<img width="48" alt="Screenshot 2024-10-20 alle 11 07 38" src="https://github.com/user-attachments/assets/0f24c8ab-6765-45bf-ba89-18132b78d345">
<img width="48" alt="Screenshot 2024-10-20 alle 11 07 52" src="https://github.com/user-attachments/assets/490e1386-de3e-4adb-bc49-b2393c888710">

Yes it's an important information and it should be visible listed but not as a dot. It just occupies space of other calendars colors.
Tried to disable this option in Calendar settings but ended up also not showing the birthdays anymore.

Feedback? Could we also add the option to be visible on the month view or not?

**Comment by pakerwreah** [comment]
That's a very specific use case, and will require adding another option in Preferences.

If you need to see that many calendar in the menu bar, with events in every single day, I would suggest disabling birthdays altogether.

**Comment by ilMagnifico** [comment]
> 

I get it.
