### ISSUE TITLE
Add option to move Reminders/Calendar list on the way

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#266]
<img width="353" alt="Screenshot 2024-10-20 alle 11 14 28" src="https://github.com/user-attachments/assets/dda88fc8-8036-496c-929f-5b83974a1de4">

Wouldn't be nice to have also the option to move the reminder/calendar to another list? Perhaps adding another button before this sating "Move..."

**Comment by pakerwreah** [comment]
I don't have enough information from Apple's api to identify what is a "list" or just another calendar.

That's also stepping into editing territory, which is not the focus of Calendr.
