### ISSUE TITLE
Buttons should have info where you leave the cursor on them

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#267]
<img width="330" alt="Screenshot 2024-10-20 alle 11 17 23" src="https://github.com/user-attachments/assets/ee87872e-3a69-4a6e-9b24-41d892b21562">
I know what these buttons do, but they may be consuming for newbies, so maybe adding the effect that when you leave the cursor on them for a couple of seconds just tells you "pin the calendar", "open reminders" etc.

**Comment by pakerwreah** [comment]
I'm pretty sure people will click them before reading the tooltip.

I will also have to localize them in 10 different languages. It's not a game changer to worth the effort.

**Comment by ilMagnifico** [comment]
> I'm pretty sure people will click them before reading the tooltip.
> 
> I will also have to localize them in 10 different languages. It's not a game changer to worth the effort.

It's a long term investment though.

**Comment by pakerwreah** [comment]
Yeah, I'm just being lazy here.

I will do it for English and Portuguese and ask you to open a PR with Italian later.
When it's done, you can follow the link in [MISSING_TRANSLATIONS.md](https://github.com/pakerwreah/Calendr/blob/master/MISSING_TRANSLATIONS.md) and edit the file directly from Github.
The missing texts will be commented out, you just have to remove the `//` and change the text.

I will let you know here.

**Comment by pakerwreah** [comment]
Go for it 🚀 🌐 ✍🏻
