### ISSUE TITLE
Menu bar icon text is hard to read

### ISSUE THREAD

**Issue by zhanglolo** [pakerwreah/Calendr#275]
![QQ_1730884690908](https://github.com/user-attachments/assets/894cfe6b-4e31-4ae4-aa45-11d00112a10f)

In contrast, text is not so easy to read, can there be a setting to adjust it individually.

**Comment by pakerwreah** [comment]
Could you be more specific?

**Comment by zhanglolo** [comment]
On the left is Itsycal, and on the right is Calendar.

The text of Calendar is too thin to look blurry on the screen. Can you add a setting to adjust the size and thickness of the font?

**Comment by pakerwreah** [comment]
you mean the left one is Calendr?
