### ISSUE TITLE
Menu bar date is invisible if icon is disabled

### ISSUE THREAD

**Issue by laurentNoudohounsi** [pakerwreah/Calendr#285]
Hello 👋

It seems that version 1.14.3 has introduced an issue.
When the 'Show icon' option is disabled, the date in the menu bar becomes hidden.

![Screenshot 2024-11-10 at 22 21 20](https://github.com/user-attachments/assets/dba78fe0-9756-4375-97ec-e77ea47300c4)

**Comment by pakerwreah** [comment]
oh shit 😆 yeah

**Comment by pakerwreah** [comment]
The funniest part is that it was something I removed thinking "why the hell did I put this here?"

**Comment by laurentNoudohounsi** [comment]
> The funniest part is that it was something I removed thinking "why the hell did I put this here?"

Well know... We know 😅😂😂😂
I feel you, we all do that 😅
