### ISSUE TITLE
Missing Translations (hardcoded strings)

### ISSUE THREAD

**Issue by bhopmann** [pakerwreah/Calendr#287]
Here are some hardcoded strings, where translations are currently missing.

https://github.com/pakerwreah/Calendr/blob/4c232e399955e9fbf2d62ba6cbeef4e7f5a18954/Calendr/Settings/SettingsViewModel.swift#L203-L207

https://github.com/pakerwreah/Calendr/blob/4c232e399955e9fbf2d62ba6cbeef4e7f5a18954/Calendr/Main/MockMainViewController.swift#L74-L79

**Comment by pakerwreah** [comment]
I'm not sure what you mean.
The first one literally says `localizedUnit`.
The second one is just a mock for UI tests.

**Comment by bhopmann** [comment]
I'm using macOS Sequoia 15.1 
And my calendar (and the whole system as well) is actually set to german

**Comment by pakerwreah** [comment]
Does it say "Other" inside the native Calendar app?

**Comment by bhopmann** [comment]
No, it says "Andere":

<img width="140" alt="Bildschirmfoto 2024-11-11 um 16 12 21" src="https://github.com/user-attachments/assets/6f3e82db-2589-4003-998f-493b5fd51922">

**Comment by pakerwreah** [comment]
Ok, I will change my system to another language and see what's going on.
I'm getting it directly from Apple's api, so I have no idea why it is defaulting to English.

**Comment by pakerwreah** [comment]
Broken into separate issues.
