### ISSUE TITLE
[Feature Request] Show video button for Webex

### ISSUE THREAD

**Issue by bhopmann** [pakerwreah/Calendr#293]
Currently MS Teams and Zoom are supported (see #4). I would like to suggest to support Webex as well (see Webex URL requests https://developer.cisco.com/docs/webex-meetings/url-api/#url-api-command-structure).

**Comment by pakerwreah** [comment]
That doesn't help much, could you give real meeting URL examples? (redacting sensitive information)

**Comment by bhopmann** [comment]
A Webex-Meeting-URL for a scheduled meeting looks like this: `https://mycompany.webex.com/mycompany/j.php?MTID=huer7834hbfe7`

A Meeting-URL for personal meeting room: `https://mycompany.webex.com/meet/name`

**Comment by pakerwreah** [comment]
Apparently there's no url scheme to open the native app directly for those cases, but I will try at least to identify the URL, as I do for Google meetings and Hangout, and display the video button.

**Comment by pakerwreah** [comment]
Please check if this works for you: [Calendr.zip](https://github.com/user-attachments/files/18216297/Calendr.zip)

**Comment by bhopmann** [comment]
> Please check if this works for you: [Calendr.zip](https://github.com/user-attachments/files/18216297/Calendr.zip)

Yes, it does – thank you!
