### ISSUE TITLE
Feature - Popup when the meeting starts

### ISSUE THREAD

**Issue by mathieuletyrant** [pakerwreah/Calendr#294]
A popup notification will appear on your screen when the meeting begins, ensuring you don't miss the start time. The notification will temporarily block your view to grab your attention and inform you that the meeting is now in session.

**Comment by pakerwreah** [comment]
Please see this discussion:
- https://github.com/pakerwreah/Calendr/discussions/283

But I think if it's just a simple popup with "Close" and "Join" buttons, I can make that an option.

**Comment by pakerwreah** [comment]
I don't understand, though, why people disable the native alert notifications if this is something people want.

**Comment by mathieuletyrant** [comment]
I have the notifications 🙈
But even when I'm focused, I don't look at them. That's why I wanted a full-screen notification to alert me.
