### ISSUE TITLE
Is it possible to disable the new additional notification sounds frequency?

### ISSUE THREAD

**Issue by mapleroyal** [pakerwreah/Calendr#295]
I don't see a setting for this, but however it worked prior to this change was awesome. I feel like the new sound happens more often than the number of alerts I have for a given event. Am I imagining that?

It's nice if you can configure it, but all calendar services already handle this functionality by adding extra alerts per event. I typically set an alert 1hr prior and then 5min prior.

So with the new sounds I have 2 notification sounds already, then it seems like another extra 3 or so right as the event is about to start which can be quite distracting (not good) or becomes background noise if it's happening so often (dangerous, because you don't want to miss calendar alerts).

The visual flashing is nice, I guess. I don't remember that before but I don't have a strong opinion one way or the other.

**Comment by pakerwreah** [comment]
The alerts are not synchronized with the system, they always happen 5min + 1min before the event, and a different one when the event starts.

I'm gonna add a setting to disable the sounds.

The red flashing happens in the last 5 minutes. Every minute it flashes 5x until the event start.
