### ISSUE TITLE
Feature request: ability to disable sounds

### ISSUE THREAD

**Issue by nileane** [pakerwreah/Calendr#296]
I think it could be nice if we could disable the new sounds for upcoming events.
Right now the only option, as far as I can tell, is to disable alerts entirely for each calendar.

**Comment by pakerwreah** [comment]
I will add a new setting to disable them 👍🏻

**Comment by pakerwreah** [comment]
@nileane I just found the podcast where you mentioned this.
No wonder I started getting so many users in 2024 😂

**Comment by nileane** [comment]
> @nileane I just found the podcast where you mentioned this.
> No wonder I started getting so many users in 2024 😂
> 

Haha yes! Sorryyyyy
