### ISSUE TITLE
Big Sur menu style

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#30]
Would it be possible to remove the small arrow pointing to the icon to make it more Big Sur style menu like the other menu bar items? I mean this:
<img width="120" alt="Captura de pantalla 2021-03-17 a las 14 19 17" src="https://user-images.githubusercontent.com/823394/111466405-eb8a8780-872b-11eb-8d3c-e4bb35f16ba0.png">

**Comment by pakerwreah** [comment]
This is a widget, not a menu list, and it's the popover's native behavior. I actually chose to use popovers because of that.
