### ISSUE TITLE
[Feature Request] Display events in local time zone

### ISSUE THREAD

**Issue by nikjobe** [pakerwreah/Calendr#302]
Currently, the app displays the time zone associated with a specific event. It would be beneficial to include an option to show all events in the local time zone. For instance, in the provided screenshot, the event was entered into the calendar with a time of 13:15-15:00 UTC. However, in my time zone, it actually occurs from 14:15-16:00.
![screenshot](https://github.com/user-attachments/assets/ced8fe35-1f46-4d38-9a22-c162dcc076a3)

**Comment by pakerwreah** [comment]
Currently only meetings are displayed in your local timezone.
I can add an option to force everything to be the same.
