### ISSUE TITLE
'Show icon' is not unselectable

### ISSUE THREAD

**Issue by sms-cx** [pakerwreah/Calendr#304]
The option for show icon under the menu bar settings is not unselectable. I want only the next event to show up and that doesn't seem to work.

**Comment by pakerwreah** [comment]
Yeah, that's intended. If you hide everything, there's no way to access the app settings anymore.

**Comment by pakerwreah** [comment]
You can hide it if you show the date. You need to have one of them or both.

**Comment by pakerwreah** [comment]
@sms-cx this will be implemented in v1.19.2
