### ISSUE TITLE
Notch not handled correctly

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#309]
If the notch option is enabled
<img width="572" alt="Screenshot 2024-12-09 alle 23 51 27" src="https://github.com/user-attachments/assets/3dcaa99b-29d2-4c61-b213-03c22b9dce33">
<img width="366" alt="Screenshot 2024-12-09 alle 23 51 37" src="https://github.com/user-attachments/assets/d9295d45-a891-497a-97e6-33ea40e0a593">

If disabled
<img width="378" alt="Screenshot 2024-12-09 alle 23 51 40" src="https://github.com/user-attachments/assets/a9b8945d-f65e-4844-a7fe-69e1637ea436">
<img width="598" alt="Screenshot 2024-12-09 alle 23 51 46" src="https://github.com/user-attachments/assets/8b0000d2-fa6d-461b-8d4d-06545124f5c9">

As you can see, there is enough space for displaying al the info of the reminder, even though it's not displayed if the option is enabled, even if the text would not overlap notch.

**Comment by pakerwreah** [comment]
I'm not measuring the distance between the view and the notch, I'm just shrinking it.
Event if there was a way to do that, I would have to know if you have other menu bar items at the left of the event.
This feature is far from perfect, but it helps. If you have a lot of space on your menu bar, you can disable it.

**Comment by ilMagnifico** [comment]
I experienced some strange behavior a couple of days ago, but it’s still too vague to report. 

Depending on the enabled/disabled setting and the connected display (with the MacBook acting as a second display), sometimes events/reminders wouldn’t appear in the top bar of the MacBook, even though they were visible on the main display.

**Comment by pakerwreah** [comment]
If the menu bar item touches the notch it disappears completely and leave a big blank space behind.
That's why I have this feature to shrink it and avoid that issue.
