### ISSUE TITLE
Losing focus of active window when opening the menu bar calendar

### ISSUE THREAD

**Issue by nhat** [pakerwreah/Calendr#311]
How to reproduce:

1. Have an active window from any app, e.g., Safari.
2. Click on the calendar menu icon or use the hotkey.
3. Expected: The current active window stays focused, like clicking other menu bar items.
4. Actual: The current active window loses focus.

Sonoma 14.7.1
Calendr V1.14.7

This is especially troubling when using only the keyboard since refocusing the window is not possible with cmd+tab/cmd+` because the app is still in the foreground.

**Comment by pakerwreah** [comment]
You cannot interact with the calendar if it is not focused.
Menu bar items that don't change focus are menu-based ones, not window-based.
There are technical limitations.

**Comment by pakerwreah** [comment]
That might be a limitation from when I was using native popovers. I will have a second look.

**Comment by pakerwreah** [comment]
I hope this doesn't break my entire app 😅

**Comment by PuzzledUser** [comment]
Sadly, the menu popover has now retired behind notifications (not in front). Perhaps this is the ~~droid~~ break you were looking for? 🤣 See https://github.com/pakerwreah/Calendr/issues/180.
