### ISSUE TITLE
Parsing additional calendar event section

### ISSUE THREAD

**Issue by m1h4** [pakerwreah/Calendr#312]
Not sure if this is a Meet-specific format, but Google Calendar events created with a Meet link have a special section in the calendar event description that gives connection information
<img width="450" alt="Screenshot 2024-12-12 at 14 20 45" src="https://github.com/user-attachments/assets/ac6aa9de-429d-4afa-81af-ab9c52bfaefd" />:

the section can be found by looking for:
`-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-\n`
and ends with another
`-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-\n`

Apple calendar from recent MacOS versions started supporting this syntax and just displays the text inside this section as a separate description section above the regular description:
<img width="301" alt="Screenshot 2024-12-12 at 14 20 59" src="https://github.com/user-attachments/assets/88a347f9-e39c-47a9-9dd2-18883db7c0e4" />

so note that in the actual ICAL document the regular description precedes this section, in the parsed UI the meeting connection section is placed above the regular description.

Seems like something that should be straightforward to implement and support, would make looking at calendar events with Meet links much nicer!

Maybe even have a Preferences toggle under Appearance for showing/hiding this section.

**Comment by pakerwreah** [comment]
That shouldn't be a problem to implement, but does it make sense?

I think the regular description is more relevant than the connection details, since I'm already showing the link at the very top, which can be opened in the preferred browser.

How many times did you have to dial that phone number to join the meeting? 😅

**Comment by pakerwreah** [comment]
To answer your first question, yes, that seems to be a meeting-specific format, at least I get the same syntax for Zoom.

**Comment by m1h4** [comment]
> That shouldn't be a problem to implement, but does it make sense?
> 
> I think the regular description is more relevant than the connection details, since I'm already showing the link at the very top, which can be opened in the preferred browser.
> 
> How many times did you have to dial that phone number to join the meeting? 😅

True, I’m actually totally fine with having that filtered out. It’s just that in it’s current form where it’s just left in the description verbatim makes it noisy and visually harder to quickly parse out the actual description from this metadata.

**Comment by pakerwreah** [comment]
I will try to separate it into a nice looking section, but it will probably stay at the bottom.

**Comment by m1h4** [comment]
That sounds great, thank you! Looking forward to the update!
