### ISSUE TITLE
Open reminder/event on the native app clicking on them

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#313]
Regarding what was written in #305, I agree that adding too many features, such as editing or deleting the event, would be excessive, but at least we could make it more convenient. Double-clicking the event open the full event description, and from there, we could for example add a button in the interface to open the event/reminder in the native app, or something similar, because objectively, if I want to modify or delete it, I have to start from scratch in the native app. 

A redirect between Calendr and the native app that takes me directly to the event/reminder to modify/delete would be convenient and a nice addition.
<img width="637" alt="Screenshot 2024-12-13 alle 23 57 58" src="https://github.com/user-attachments/assets/0840a3a1-cac1-45b9-abb6-d2365a795a41" />

**Comment by pakerwreah** [comment]
If you right click the event there's an `Open` button that does exactly that.

**Comment by ilMagnifico** [comment]
> If you right click the event there's an `Open` button that does exactly that.

Just discovered it, thanks! Wouldn’t it be better to also add a small button in the event/reminder detail view for the same action? It would make sense for follow-ups, if needed, right from that view.
<img width="631" alt="Screenshot 2024-12-14 alle 00 37 21" src="https://github.com/user-attachments/assets/6ddd61b5-e099-4075-beeb-35b51ce886a8" />

What do you think?

**Comment by ilMagnifico** [comment]
If makes sense to have all the option you have here:
<img width="168" alt="Screenshot 2024-12-14 alle 00 41 24" src="https://github.com/user-attachments/assets/13a8b10f-b9ca-4ba5-a2cb-08ce6886619a" />

Also here:
<img width="295" alt="Screenshot 2024-12-14 alle 00 41 16" src="https://github.com/user-attachments/assets/895f4aa5-2eca-46e7-9474-da83937bc13f" />

**Comment by pakerwreah** [comment]
That same button for events is your meeting status selector.
I will see if I can create a separate button for that inside the details popup.
