### ISSUE TITLE
URL-scheme for accessing Calendr and writing macOS calendar events

### ISSUE THREAD

**Issue by martinengelke** [pakerwreah/Calendr#314]
I would like to use my launcher (https://albertlauncher.github.io) to show up events in Calendr.
I am using Itsycal right now which has the ability to at least jump to a date like: 

> Itsycal has a URL scheme: itsycal://date/DATE which will open Itsycal at the DATE specified in yyyy-MM-dd format. Instead of DATE use now to open Itsycal to today.

There is an **Alfred workflow** existing, but I do not own Alfred and I **don't** want to trigger the **macOS calendar itself**, instead I would like the **system tray of Calendr** to open, showing me the actual date or add an entry. [Alfred Calendar Extension](https://github.com/rtoshiro/alfred-workflows-addcalendarevent)

There's also an [RayCast Extension](https://github.com/raycast/extensions/blob/36abdaacac9b02cbbc54dbe33f16b6c40cd23f54/extensions/menubar-calendar/swift/AppleReminders/Sources/Calendar.swift) which shows how it can work:

> Use ekEvent.calendarItemIdentifier, (not the ekEvent.eventIdentifier)
> Date format: yyyyMMdd'T'HHmmss'Z'
> Create URL: ical://ekevent/(date)/(eventIdentifier)?method=show&options=more

Also an [Apple Page](https://developer.apple.com/library/archive/documentation/AppleApplications/Conceptual/CalendarScriptingGuide/Calendar-CreateanEvent.html#//apple_ref/doc/uid/TP40016646-CH94-SW3), maybe helpful.

And here is a repository showing the wide use of URL schemes in general:
https://github.com/SKaplanOfficial/macOS-URL-Schemes-for-macOS-Applications

In the end I would be fine having something like 
calendr://date/%s
calendr://addevent/%s

For the date value it would be phenomenal to have options like 

```
yesterday
today, 
tomorrow, 
this/next/last week, 
in x days/weeks/month, 
2024-12-31
1st of September 2025
```

For the addevent value:
```
at 14 on 21 dur 1 h
at 14 tomorrow alarm 0 m 10 h 5 days 1 month 1 year
at 14 on 21/04 alarm 1 d 5 days
today
tomorrow
at 15 on 28/03/13 dur 4 days
on 25 every year
at 15 every monday
every month
at 15 on 28 in Museum alarm 10 d 2 months
at 11pm on 23
at 10 pm today dur 2 h
at 9pm tomorrow alarm 5 days
at 11 am tomorrow
at 11 tomorrow
at 15 on friday
at 14 on mon
at 2pm on saturday
at 2pm on sat every day
```

Thank you very much!

Best wishes to Coimbra, I am living in the Distrito de Castelo Branco.

**Comment by pakerwreah** [comment]
Thanks! I just wanted to be sure of how you were using it.
For example, I would have not considered the natural language values.

I was asked to do something similar in the search feature, to be able to jump to a specific date, but I still have to do some research and see if macOS has native APIs to parse date strings like that, in the user's locale.

Regarding the `addevent` scheme, Calendr does not support adding events.

**Comment by martinengelke** [comment]
Hey, cool !
I will try it out.

**Comment by martinengelke** [comment]
Works fine, thank you very much
