### ISSUE TITLE
Menubar text is a bit lower than the system elements (clock, weather)

### ISSUE THREAD

**Issue by m1h4** [pakerwreah/Calendr#317]
The menubar text seems to be slightly lower than what the system elements use:
<img width="2130" alt="Screenshot 2024-12-16 at 09 31 06" src="https://github.com/user-attachments/assets/28cbb380-c53b-464c-88ee-33026051b7f4" />

this is with the font size reduced by one notch:
<img width="2403" alt="Screenshot 2024-12-16 at 09 33 58" src="https://github.com/user-attachments/assets/04971e66-de5b-4a02-9433-d1f117afd02d" />

it seems to be off by maybe one point or two. Would be nice if it was all aligned if the font size is configured to be the same.

**Comment by pakerwreah** [comment]
It is aligned with the icons, the system one looks off.

**Comment by m1h4** [comment]
![9dxf5i](https://github.com/user-attachments/assets/cd090def-54f3-470f-b03d-08df17d492c4)

**Comment by pakerwreah** [comment]
hahahaha nice one 🤣
