### ISSUE TITLE
Narrow list of events of the day

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#329]
<img width="343" alt="Screenshot 2024-12-26 alle 22 18 46" src="https://github.com/user-attachments/assets/28456649-a614-45aa-a542-9998681a94f0" />

While with the setting for showing also completed events enabled everything seems fine.
<img width="327" alt="Screenshot 2024-12-26 alle 22 19 02" src="https://github.com/user-attachments/assets/92b361be-8b7a-432a-beaf-7494677447ad" />

**Comment by pakerwreah** [comment]
I would have to see the contents to figure out what's happening.
Can you check with v1.14.7 ?

**Comment by pakerwreah** [comment]
nvm, just found the issue.

**Comment by ilMagnifico** [comment]
> nvm, just found the issue.

Super Carlos! 😄
