### ISSUE TITLE
first day of the week

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#5]
It would be good if it could read from the system settings the first day of the week and show the month calendar accordingly. At the moment it shows Sunday as first day of the week even my system has it set to Monday

**Comment by pakerwreah** [comment]
I have to see if I can extract this info from the system.
But I can always create a new in-app setting for that.

**Comment by gferreroferri** [comment]
Yes, that should make it

**Comment by pakerwreah** [comment]
[Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/5896072/Calendr.app.zip)
