### ISSUE TITLE
Reminders icon looks more like alarm

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#50]
Somehow the bell icon looks more like alarms than actually tasks. Maybe something closer to it like checklist from SFSymbol? 
![checklist@2x](https://user-images.githubusercontent.com/823394/127615606-1679b20d-8776-45e2-b6be-4507883c380f.png)

**Comment by pakerwreah** [comment]
I swear I didn't find this icon 🤔 
at least it's not here:
https://sfsymbols.com

There's a bullet list, but it didn't sound very related to reminders. Do you think it's better?

**Comment by gferreroferri** [comment]
It seems to be only available in the new SFSymbol beta, so I guess only Monterrey😞 
But yes, the bullet list is good and closer to reminders
