### ISSUE TITLE
Wrong date span for first week day greater day month start 

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#51]
Hi,

See the video to understand the problem. Bug when selecting a day outside the current month where week is partially in current month

https://user-images.githubusercontent.com/823394/127731379-a6bcd0e4-ade4-4428-934b-049130cdcfa5.mov

**Comment by pakerwreah** [comment]
This is actually not related to the selection.
The app is not showing the first week of August in your configuration (Monday being the first day of week).
