### ISSUE TITLE
Is it possible to add a vietnamese lunar calendar?

### ISSUE THREAD

**Issue by ghost** [pakerwreah/Calendr#58]
Hello,

my girlfriend is from vietnam and unfortunately I haven't found a beautiful calendar app or something similar that shows the vietnamese lunar calendar. Is it possible to support this?

**Comment by pakerwreah** [comment]
Do you want the entire calendar changed or you just want to see the lunar dates alongside the gregorian dates?

You can currently change you region and some other configurations in `System Preferences > Language & Region`

I couldn't find vietnamese, but some of those options follow the lunar calendar.

<img width="668" alt="Screenshot 2021-08-23 at 17 00 38" src="https://user-images.githubusercontent.com/803954/130511653-38129616-837c-45ad-ac58-c65e851a93bf.png">

**Comment by tobiegsmusc** [comment]
It is enough if the vietnamese lunar dates are below the gregorian dates. 

Here is a third party app that my girlfriend uses on her iPhone. So you can see what it looks like.
https://apps.apple.com/us/app/vlunar-%C3%A2m-l%E1%BB%8Bch-widget/id1531851878

I think there is no operating system that has the vietnamese lunar calendar integrated, so you won't find it in the system preferences.

**Comment by pakerwreah** [comment]
I think the closest we have support in code is the chinese calendar. I have no idea what are the differences though.

I will leave this issue open to see if we get some help.
