### ISSUE TITLE
Window is jumping when choosing some dates

### ISSUE THREAD

**Issue by mrdumont1** [pakerwreah/Calendr#62]
Hi,

I found a little bug:

https://user-images.githubusercontent.com/89343804/154928354-e27c498d-3882-41f1-80b1-2536593d3c67.mov

It seems this occurs when the list of events is getting too large.

Greetings

**Comment by pakerwreah** [comment]
Thanks! I will have a look at this 🙇🏻

**Comment by mrdumont1** [comment]
That was fast ;-) Thank you. Great work!

Am Mo., 21. Feb. 2022 um 20:50 Uhr schrieb Carlos Enumo <
***@***.***>:

**Comment by pakerwreah** [comment]
There's another issue in your video 😅 #64
