### ISSUE TITLE
Add resizing option for drop-down calendar

### ISSUE THREAD

**Issue by jajugoguma** [pakerwreah/Calendr#66]
Thanks for making such a great calendar app!

By the way, I wish there was an option to resize the dropdown layer.(based on size or width or font size. I’m okay with any option.)
Personally, it feels like the dates on the calendar are small and close together so I can't see them at a glance.

If you add it, I would be really really really happy.
Thank you! 😄

**Comment by pakerwreah** [comment]
That can be a nice improvement. I will see what I can do 👍🏻

**Comment by pakerwreah** [comment]
Could you check if this solves your issue?
https://github.com/pakerwreah/Calendr/releases/tag/v1.5.0

**Comment by pakerwreah** [comment]
Check out the pre-release [v1.5.0-rc](https://github.com/pakerwreah/Calendr/releases/tag/v1.5.0)

I usually wait a few days to fully release it to be sure I don't ship any nasty bugs 🐞

**Comment by jajugoguma** [comment]
Thank you! 

It is what I wanted! I'm looking forward to a full release!

![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/41339744/162340734-bc9f618b-ed6c-43a6-b0ff-58240075d91c.gif)
