### ISSUE TITLE
Event info popover

### ISSUE THREAD

**Issue by pakerwreah** [pakerwreah/Calendr#7]
Open a popover by clicking the event to show extra info like url, location, notes, organizer, people invited.

**Comment by gferreroferri** [comment]
Also add an option on that pop over to open the event in macOS calendar app

**Comment by pakerwreah** [comment]
I've already tried, but I don't think there's a way to do that.

I even tried to run an Apple Script to do that, opening the calendar and simulating a click on the event. The closed I got was to open the calendar with the event selected, but not open. 😞

**Comment by gferreroferri** [comment]
At least opening the calendar with event selected is already some good way to locate the event in the calendar app. That would be already useful
