### ISSUE TITLE
Process is running but does not appear in menu bar

### ISSUE THREAD

**Issue by abakhru** [pakerwreah/Calendr#75]
- current builds doesn't work on m1 (arm) based macos

**Comment by pakerwreah** [comment]
It does. I'm running it on a M1 Pro.

**Comment by abakhru** [comment]
- i have m1 max, process is running but nothing shows up in the menu-bar.
<img width="819" alt="image" src="https://user-images.githubusercontent.com/6353452/175771276-86eab07b-74e7-4e8b-94fe-b7cd47543efe.png">

- not seeing any logs, so not sure where to debug 
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/6353452/175771323-35567786-0504-4a50-bded-778df90fb312.png">

**Comment by abakhru** [comment]
tried reinstalling the app after cleaning it up. still not working

**Comment by pakerwreah** [comment]
Do you use any menu bar manager, like Bartender?
