### ISSUE TITLE
Icon in the menu bar looks a bit too big

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#89]
Compared with other menubar icons, the Calendr icon seems a bit too big (see screenshot). Would it be possible to adjust it to fit better with the others? 
<img width="303" alt="Captura de pantalla 2022-12-02 a las 16 23 33" src="https://user-images.githubusercontent.com/823394/205314430-3b79d7fa-b46f-4c76-86fb-75c4acc3aeb6.png">

**Comment by pakerwreah** [comment]
Yeah, sure. I will adjust it. 👍🏻
