### ISSUE TITLE
Overdue tasks in today's view

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#91]
Add an option to show on today's view overdue tasks from previous days

**Comment by pakerwreah** [comment]
I will use this version for a few days before releasing. (it was not a trivial change)
Please, help me test it.
[Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/10149691/Calendr.app.zip)

**Comment by gferreroferri** [comment]
thanks! I have just installed it and will test it as well
