### ISSUE TITLE
Popup jiggles on date change

### ISSUE THREAD

**Issue by ismslv** [pakerwreah/Calendr#98]
When switching between dates, calendar jiggles. Looks unintended.

<img src="https://s9.gifyu.com/images/Screen-Recording-2022-12-14-at-02.08.32.gif" width="400px"/>

**Comment by ismslv** [comment]
> That's weird, I'm not able to reproduce this at all in my machine. Do you use any kind of menu bar manager? What version of macOS do you have?

- macOS Ventura 13.0.1
- MacBook Pro M1 14
- No menubar managers

I retested and this happens only on the main macbook screen, but does not happen on any external monitor.

If I change the "scale" for the main screen in **Settings > Monitors** (there are five possible scales), jiggle happens on all of them except the middle one (for me, it is not a default one, default is fourth).

**Comment by ismslv** [comment]
> I happens **_only_** with the middle one for me 😆 Can you tell me your screen resolution?

BetterDisplay tells it's 1512x982 HiDPI. In the Settings there is no label with a real resolution.

**Comment by pakerwreah** [comment]
Could you check if this build fixes the issue for you?
[Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/10233108/Calendr.app.zip)

**Comment by ismslv** [comment]
> Could you check if this build fixes the issue for you? [Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/10233108/Calendr.app.zip)

Almost. That big jiggle is gone, now it just jumps vertically one time when first date is selected.

<img src="https://s9.gifyu.com/images/ezgif.com-gif-maker6856c9642326f2c5.gif" width="400px" />

**Comment by pakerwreah** [comment]
Ok, try this one 🙏🏻🤞🏻
[Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/10237890/Calendr.app.zip)

**Comment by ismslv** [comment]
> Ok, try this one 🙏🏻🤞🏻 [Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/10237890/Calendr.app.zip)

👍 On the main screen all is stable. On other screens it started to move a little horizontally or vertically (different on different screens) but it is negligible, as it happens only after the switch (when I open popover on different screen than the last time).

Also there is a very big jump during such a switch, if I don't close the popover, it will literally fly across the screens, and if I close it and then open on the other screen, it will briefly appear in the bottom corner and then reappear in the correct place. No other menubar popover does this.

**Comment by pakerwreah** [comment]
It's not jiggling anywhere for me now, can you show me a video?

This weird jump is "normal" but I will see if I can disable the animation in that situation.

About it appearing in the bottom corner, I also need a video, because I'm not experiencing any glitches anymore.

**Comment by pakerwreah** [comment]
Do you want to discuss this over Twitter / Skype / WhatsApp or whatever?
I feel this is going to take some time to solve 😅 

You can send me your contact on [@pakerwreah](https://twitter.com/pakerwreah)
